# Generated by Django 5.1.3 on 2025-12-05 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('VEG', 'Veg'), ('NON-VEG', 'Non-veg')])),
                ('meal_category', models.CharField(choices=[('MORNING BREAKFAST', 'Morning Breakfast'), ('MORNING LUNCH', 'Morning Lunch'), ('AFTERNOON LUNCH', 'Afternoon Lunch'), ('EVENING LUNCH', 'Envening Lunch'), ('NIGHT DINNER', 'Night Dinner')], default='MORNING BREAKFAST')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VEG', 'Veg'), ('NON-VEG', 'Non-veg'), ('BOTH', 'Both')], default='VEG', max_length=20)),
                ('category', models.CharField(choices=[('MORNING BREAKFAST', 'Morning Breakfast'), ('MORNING LUNCH', 'Morning Lunch'), ('AFTERNOON LUNCH', 'Afternoon Lunch'), ('EVENING LUNCH', 'Evening Lunch'), ('NIGHT DINNER', 'Night Dinner')], max_length=50)),
                ('no_of_consumer', models.IntegerField(default=1)),
                ('preferences', models.TextField()),
                ('meals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='khaja.combo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('ingridents', models.CharField(max_length=50)),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaja.meals')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaja.meals'),
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('energy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('protien', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaja.meals')),
            ],
        ),
    ]
