# Generated by Django 5.1.3 on 2025-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='meals',
        ),
        migrations.AddField(
            model_name='combo',
            name='meals',
            field=models.ManyToManyField(to='khaja.meals'),
        ),
    ]
