# Generated by Django 5.1.3 on 2025-12-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('VEG', 'Veg'), ('NON-VEG', 'Non-veg'), ('BOTH', 'Both')])),
                ('meal_category', models.CharField(choices=[('MORNING BREAKFAST', 'Morning Breakfast'), ('MORNING LUNCH', 'Morning Lunch'), ('AFTERNOON LUNCH', 'Afternoon Lunch'), ('EVENING LUNCH', 'Envening Lunch'), ('NIGHT DINNER', 'Night Dinner')], default='MORNING BREAKFAST')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_servings', models.IntegerField(default=1)),
                ('preferences', models.TextField()),
                ('delivery_time', models.DateTimeField()),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaja.meals')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('energy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('protien', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaja.meals')),
            ],
        ),
    ]
