# Generated by Django 5.1.3 on 2025-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaja', '0002_meals_custommeal_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
