# Generated by Django 5.1.3 on 2025-12-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khaja', '0003_alter_meals_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='meal_id',
            new_name='meal',
        ),
    ]
