# Generated by Django 5.1.3 on 2025-12-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khaja', '0004_rename_meal_id_nutrition_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='meal',
            new_name='meal_id',
        ),
    ]
